quarkus.datasource.db-kind=sqlite
quarkus.datasource.jdbc.url=jdbc:sqlite:berkasdb.sqlite
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true

# CORS configuration so SvelteKit frontend can call this backend
quarkus.http.cors=true
quarkus.http.cors.origins=*
quarkus.http.cors.methods=GET,PUT,POST,DELETE,OPTIONS
quarkus.http.cors.headers=accept, authorization, content-type, x-requested-with
